
--------------------------------------------
-- DASHBOARD 1
-- SALES PERFORMANCE
--------------------------------------------

-- 1.
-- Business Overview KPIs

select count(distinct order_id) as Total_Orders,
count(distinct dim_customer_key) as Total_Customers,
round( sum(cast(procured_quantity as float) * cast(unit_selling_price as float)), 2) 
as Gross_Revenue,
round( sum((cast(procured_quantity as float) * cast(unit_selling_price as float))
 - cast(total_discount_amount as float)), 2 ) as Net_Revenue,
round( sum( (cast(procured_quantity as float) * cast(unit_selling_price as float))
- cast(total_discount_amount as float)) / count(distinct order_id),  2) as AOV,
round( sum(cast(total_discount_amount as float)) * 100.0 / sum(cast(procured_quantity as float)
* cast(unit_selling_price as float)), 2 ) as Discount_Rate_Percentage
from sales

-- 2.
-- Looking at the No. of Orders, Units_Sold , Revenue , Average Order Value(AOV) per city 

select city_name as City,count(distinct order_id) as Orders,
SUM(CAST(procured_quantity as float)) as Units_Sold,
 round(sum((cast(procured_quantity as float) * cast(unit_selling_price as float))
 - cast(total_discount_amount as float)),2) as Revenue,
 round(sum((cast(procured_quantity as float) * cast(unit_selling_price as float))
 - cast(total_discount_amount as float)) * 1.0 / count(distinct order_id),2) as AOV
from sales
group by city_name
order by Revenue desc


-- 3.
-- Looking at the No.of Orders and Revenue per Day

select CAST(date_ AS DATE) AS Sale_Date,
COUNT(DISTINCT order_id) AS Daily_Orders,
SUM(CAST(procured_quantity AS FLOAT) * CAST(unit_selling_price AS FLOAT)
- CAST(total_discount_amount AS FLOAT))  AS Daily_Revenue
from sales
group by CAST(date_ AS DATE)
order by Sale_Date

-- 4.
-- Looking at the Daily Revenue Trend By City 

select date_ as Date,count(distinct order_id) as Daily_Orders,city_name,
SUM((cast(procured_quantity as float)* cast(unit_selling_price as float))
-cast(total_discount_amount as float))
as Daily_Revenue from sales
group by date_,city_name
order by date_ 

--------------------------------------------
-- DASHBOARD 2
-- PRODUCT PERFORMANCE
--------------------------------------------

-- 1.
-- Product Catalog KPIs

select count(distinct product_id) as Unique_Products,
count(distinct l0_category_id) as Unique_Product_Categories,
count(distinct manufacturer_name) as Unique_Manufacturers,
count(distinct brand_name) as Unique_Brands 
from products$

-- 2.
-- Revenue generated by each l0 category

select l0_category,COUNT(DISTINCT order_id) as Orders,
SUM(CAST(procured_quantity AS float)) as Units_Sold,
round(SUM(CAST(procured_quantity AS float)* CAST(unit_selling_price AS float)
- CAST(total_discount_amount AS float)),2) as Revenue
from sales_products
group by l0_category
order by Revenue DESC

-- 3.
-- Top 15 brands by Revenue

select top 15 brand_name as Brand_Name,COUNT(DISTINCT order_id) as Orders,
SUM(CAST(procured_quantity as float)) as Units_Sold,
round(SUM(CAST(procured_quantity as float)* CAST(unit_selling_price as float)
- CAST(total_discount_amount as float)), 2)  as Revenue
from sales_products
where brand_name is not NULL
group by brand_name
order by Revenue DESC

-- 4.
-- Top 10 Manufacturers by Revenue

select top 10 manufacturer_name as Manufacturer_Name,COUNT(DISTINCT order_id) as Orders,
SUM(CAST(procured_quantity as float)) as Units_Sold,
round(SUM(CAST(procured_quantity as float)* CAST(unit_selling_price as float)
- CAST(total_discount_amount as float)),2)  as Revenue
from sales_products
where manufacturer_name is not NULL
group by manufacturer_name
order by Revenue DESC

-- 5.
-- Top 15 Products by Revenue

select top 15 product_name as Product_Name,
count(distinct order_id) as Orders,
sum(cast(procured_quantity as float)) as Units_sold,
round(sum((cast(procured_quantity as float)* cast(unit_selling_price as float))
- cast(total_discount_amount as float)),2) as Revenue
from sales_products
group by product_name
order by Revenue desc

-- 6.
-- Looking at Discount intensity by category

select l0_category,round(sum(total_discount_amount),2) as Total_discount,
round(sum(procured_quantity * unit_selling_price),2) as Gross_Revenue,
round(sum(total_discount_amount) * 100.0 /sum(procured_quantity * unit_selling_price),2) 
as Discount_percentage
from sales_products
group by l0_category
order by Discount_percentage desc

-- 7.
-- Profit & Gross Margin Analysis

select l0_category,
round(sum((procured_quantity * unit_selling_price)- total_discount_amount
 - total_weighted_landing_price),2) as estimated_profit,
round((sum((procured_quantity * unit_selling_price)- total_discount_amount
 - total_weighted_landing_price) * 100.0)
/sum((procured_quantity * unit_selling_price) 
 - total_discount_amount),2) as gross_margin_percentage
from sales_products
where l0_category <> 'Specials'
group by l0_category
order by estimated_profit desc

