select top 10 * from sales

select column_name,data_type
from information_schema.columns
where table_name = 'sales'

-- Remove the duplicate Column from Sales Data

alter table sales drop column
[Column 0],[Unnamed  0 1],[Unnamed  0]

select min(date_) as start_date,max(date_) as end_date
from sales


-- Business Overview Metrics

select count(distinct order_id) as Total_Orders,
count(distinct dim_customer_key) as Total_Customers,
round( sum(cast(procured_quantity as float) * cast(unit_selling_price as float)), 2) 
as Gross_Revenue,
round( sum((cast(procured_quantity as float) * cast(unit_selling_price as float))
 - cast(total_discount_amount as float)), 2 ) as Net_Revenue,
round( sum( (cast(procured_quantity as float) * cast(unit_selling_price as float))
- cast(total_discount_amount as float)) / count(distinct order_id),  2) as AOV,
round( sum(cast(total_discount_amount as float)) * 100.0 / sum(cast(procured_quantity as float)
* cast(unit_selling_price as float)), 2 ) as Discount_Rate_Percentange
from sales

-- Looking at the No. of Orders, Units_Sold , Revenue , Average Order Value(AOV) per city 

select city_name as City,count(distinct order_id) as Orders,
SUM(CAST(procured_quantity as float)) as Units_Sold,
 round(sum((cast(procured_quantity as float) * cast(unit_selling_price as float))
 - cast(total_discount_amount as float)),2) as Revenue,
 round(sum((cast(procured_quantity as float) * cast(unit_selling_price as float))
 - cast(total_discount_amount as float)) * 1.0 / count(distinct order_id),2) as AOV
from sales
group by city_name
order by Revenue desc

-- Looking at the No.of Orders and Revenue per Day

select CAST(date_ AS DATE) AS Sale_Date,
COUNT(DISTINCT order_id) AS Daily_Orders,
SUM(CAST(procured_quantity AS FLOAT) * CAST(unit_selling_price AS FLOAT)
- CAST(total_discount_amount AS FLOAT))  AS Daily_Revenue
from sales
group by CAST(date_ AS DATE)
order by Sale_Date

-- Looking at Top 10 performing Days

select date_ as Date,
SUM((cast(procured_quantity as float)* cast(unit_selling_price as float))
-cast(total_discount_amount as float)) 
as Revenue from sales
group by date_
order by Revenue DESC

-- Looking at the Daily Revenue Trend By City 

select date_,count(distinct order_id) as Daily_Orders,city_name,
SUM((cast(procured_quantity as float)* cast(unit_selling_price as float))
-cast(total_discount_amount as float))
as Daily_Revenue from sales
group by date_,city_name
order by date_ 


-- Removed the products duplicate column 'Unnamed'

select column_name,data_type
from information_schema.columns
where table_name = 'products$'

select top 10 * from products$

-- Looking at the Product Catalog Overview

select count(distinct product_id) as Unique_Products,
count(distinct l0_category_id) as Unique_Product_Categories,
count(distinct manufacturer_name) as Unique_Manufacturers,
count(distinct brand_name) as Unique_Brands 
from products$

-- Creating a View "sales_product "

create view sales_products as
select
    s.date_,
    s.city_name,
    s.order_id,
    s.cart_id,
    s.dim_customer_key,
    cast(s.procured_quantity as float) as procured_quantity,
    cast(s.unit_selling_price as float) as unit_selling_price,
    cast(s.total_discount_amount as float) as total_discount_amount,
    cast(s.total_weighted_landing_price as float) as total_weighted_landing_price,

    p.product_id,
    p.product_name,
    p.brand_name,
    p.manufacturer_name,
    p.l0_category,
    p.l1_category,
    p.l2_category

from sales s
inner join products$ p
    on s.product_id = p.product_id

-- Revenue generated by each l0 category

select l0_category,COUNT(DISTINCT order_id) as Orders,
SUM(CAST(procured_quantity AS float)) as Units_Sold,
round(SUM(CAST(procured_quantity AS float)* CAST(unit_selling_price AS float)
- CAST(total_discount_amount AS float)),2) as Revenue
from sales_products
group by l0_category
order by Revenue DESC

-- Top 15 brands by Revenue

select top 15 brand_name as Brand_Name,COUNT(DISTINCT order_id) AS Orders,
SUM(CAST(procured_quantity as float)) AS Units_Sold,
SUM(CAST(procured_quantity as float)* CAST(unit_selling_price as float)
- CAST(total_discount_amount as float))  AS Revenue
from sales_products
where brand_name is not NULL
group by brand_name
order by Revenue DESC

-- Top 10 Manufacturers by Revenue

select top 10 manufacturer_name as Manufacturer_Name,COUNT(DISTINCT order_id) AS Orders,
SUM(CAST(procured_quantity as float)) AS Units_Sold,
SUM(CAST(procured_quantity as float)* CAST(unit_selling_price as float)
- CAST(total_discount_amount as float))  AS Revenue
from sales_products
where manufacturer_name is not NULL
group by manufacturer_name
order by Revenue DESC

-- Top 15 Products by Revenue

select top 15 product_name as Product_Name,
count(distinct order_id) as Orders,
sum(cast(procured_quantity as float)) as Units_sold,
sum((cast(procured_quantity as float)* cast(unit_selling_price as float))
- cast(total_discount_amount as float)) as Revenue
from sales_products
group by product_name
order by Revenue desc

-- Looking at Discount intensity by category

select l0_category,round(sum(total_discount_amount),2) as Total_discount,
round(sum(procured_quantity * unit_selling_price),2) as Gross_Revenue,
round(sum(total_discount_amount) * 100.0 /sum(procured_quantity * unit_selling_price),2) 
as Discount_percentage
from sales_products
group by l0_category
order by Discount_percentage desc

--  Looking at the Gross margin per category (selling price - landing price)

select l0_category,round(avg(unit_selling_price),2) as Avg_Selling_price,
round(avg(total_weighted_landing_price),2) as Avg_Landing_price,
round(avg(unit_selling_price - total_weighted_landing_price),2) as Avg_Margin_per_unit,
round(( avg( unit_selling_price - total_weighted_landing_price ) 
/nullif(avg(unit_selling_price),0)) * 100, 2) as Margin_percentage
from sales_products
group by l0_category
order by Margin_percentage desc;


select top 20
    procured_quantity,
    unit_selling_price,
    total_weighted_landing_price,
    (procured_quantity * unit_selling_price) as gross_sales
from sales_products


-- Estimated Profit by Each category

select l0_category,
count(distinct order_id) as Orders,
sum(procured_quantity) as Units_Sold,
round(sum( ( unit_selling_price * procured_quantity ) - total_weighted_landing_price 
- total_discount_amount),2) as Estimated_Profit
from sales_products
group by l0_category
order by estimated_profit desc;
